---
title: "Final Forecast"
output: html_notebook
author: Joseph Addy
---

# Instructions
# -------------
# This notebook will run right out of the box with no other steps   # needed

```{r}
source('http://faculty.cord.edu/reber/R/import.R')

import.package('fpp2')
import.package('tidyr')
import.package('dplyr')
```

```{r}
data <- read.csv('https://raw.githubusercontent.com/whyseem/Data317/master/DALY.csv')
data$val <- as.numeric(data$val)
head(data)
depression <- data %>%
  filter(cause == "Major depressive disorder") %>%
  select(year, val) %>%
  arrange(year) %>%
  select(val)
depression
drugs <- data %>%
  filter(cause == "Drug use disorders") %>%
  select(year, val) %>%
  arrange(year) %>%
  select(val)
drugs
bipolar <- data %>%
  filter(cause == "Bipolar disorder") %>%
  select(year, val) %>%
  arrange(year) %>%
  select(val)
bipolar
anxiety <- data %>%
  filter(cause == "Anxiety disorders") %>%
  select(year, val) %>%
  arrange(year) %>%
  select(val)
anxiety
names(depression)[1] <- "depression"
depression['drugs'] = drugs['val']
depression['bipolar'] = bipolar['val']
depression['anxiety'] = anxiety['val']
depression
```

```{r}
depts<-ts(depression, start=1990)
autoplot(depts, facets=TRUE)
drugsts<-ts(drugs)
autoplot(drugsts)
bipolarts<-ts(bipolar)
autoplot(bipolarts)
anxietyts<-ts(anxiety)
autoplot(anxietyts)
depts
```

```{r}
cor(depts['depression'], depts['drugs'])
fit <- tslm(depts[,'depression'] ~ depts[,'drugs'])
checkresiduals(fit)
summary(fit)
```

```{r}
(fitted <- auto.arima(depts[,'depression'], xreg=depts[,'drugs']))
```

```{r}
checkresiduals(fitted)
fitted
```

# to forecast the next 20 years I will assume drug abuse DALY will stay at the last recorded measure (736407.4)
```{r}
(fc <- forecast(fitted, xreg=matrix(rep(736407.4,20))))
autoplot(fc) + xlab("Year") + ylab("Depression DALY")
```

# I will try to improve the model by using lagged predictors and hopefully captruing the upward trend.
```{r}
Dep <- cbind(
    DepLag0 = depts[,'drugs'],
    DepLag1 = stats::lag(depts[,'drugs'],-1),
    DepLag2 = stats::lag(depts[,'drugs'],-2),
    DepLag3 = stats::lag(depts[,'drugs'],-3)) %>%
  head(NROW(depts))
Dep
```

```{r}
fit1 <- auto.arima(depts[4:28,1], xreg=Dep[4:28,1],
  stationary=TRUE)
fit2 <- auto.arima(depts[4:28,1], xreg=Dep[4:28,1:2],
  stationary=TRUE)
fit3 <- auto.arima(depts[4:28,1], xreg=Dep[4:28,1:3],
  stationary=TRUE)
fit4 <- auto.arima(depts[4:28,1], xreg=Dep[4:28,1:4],
  stationary=TRUE)
c(fit1[["aicc"]],fit2[["aicc"]],fit3[["aicc"]],fit4[["aicc"]])
```

```{r}
(laggedfit <- auto.arima(depts[,1], xreg=Dep[,1:2],
  stationary=TRUE))
checkresiduals(laggedfit)
```

```{r}
laggedfc <- forecast(laggedfit, h=20,
  xreg=cbind(DepLag0 = rep(736407.4,20),
             DepLag1 = c(Dep[28,1], rep(736407.4,19))))
autoplot(laggedfc) + ylab("Depression DALY") +
  ggtitle("Forecast Depression DALY w/ future drug abuse DALY set to 736407")
```


# Using Anxiety as single regressor

```{r}
(fitted <- auto.arima(depts[,'depression'], xreg=depts[,'anxiety']))
```

```{r}
checkresiduals(fitted)
fitted
```

```{r}
(fc <- forecast(fitted, xreg=matrix(rep(154988.2,20))))
autoplot(fc) + xlab("Year") + ylab("Depression DALY")
```



